### ISSUE TITLE
Shutter Control not working correctly

### ISSUE THREAD

**Issue by KonstantinNeuhaus** [AndriyChmyrov/Matlab#1]
Hi Andriy,
i just wanted to point out that the versions of the shutter class here on github and over on the Matlab Fileexchange are different.
The code from Fileexchange works great but the version here has errors in the following lines:

line 265:         h.OPSTATE_ACTIVE = states_enum.GetEnumValues().Get(active_enumIndx);
This line should be: h.OPSTATE_ACTIVE = states_enum.GetEnumValues().Get(active_enumIndx-1);
line 266:           h.OPSTATE_INACTIVE = states_enum.GetEnumValues().Get(inactive_enumIndx);
This line should also be: h.OPSTATE_INACTIVE = states_enum.GetEnumValues().Get(inactive_enumIndx-1);
And line 279 should be removed.

Thanks again for sharing your code!
Best,
Konstantin

**Comment by AndriyChmyrov** [comment]
Hi Konstantin,
thanks for pointing this out - I fixed the mistypes! 👍 
Regards,
Andriy
